name: Black, Pylint, MyPy
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Checks
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          # Home Assistant 2025.3.0 requires Python >=3.13.0.
          python-version: "3.13"
      - run: pip install --upgrade pip
      - run: pip install -r requirements-dev.txt
      - run: black --extend-exclude="custom_components/berlin_transport/const.py" --diff --check .
      - run: pylint $(git ls-files '*.py')
      - run: mypy $(git ls-files '*.py')
